{{- if .Values.replication.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "mysql.slave.fullname" . }}
  labels:
    app: "{{ template "mysql.name" . }}"
    chart: {{ template "mysql.chart" . }}
    component: "slave"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: {{ template "mysql.name" . }}
      release: "{{ .Release.Name }}"
      component: "slave"
  serviceName: "{{ template "mysql.slave.fullname" . }}"
  replicas: {{ .Values.slave.replicas }}
  updateStrategy:
    type: {{ .Values.slave.updateStrategy.type }}
    {{- if (eq "Recreate" .Values.slave.updateStrategy.type) }}
    rollingUpdate: null
    {{- end }}
  template:
    metadata:
      labels:
        app: "{{ template "mysql.name" . }}"
        chart: {{ template "mysql.chart" . }}
        component: "slave"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        type: "cs"
        alias: {{ .Values.kinto.alias }}
        workspace: {{ .Values.kinto.workspace }}
        blockName: {{ .Values.kinto.blockName }}
        envId: {{ .Values.kinto.envId }}
{{- if or .Values.slave.annotations .Values.metrics.enabled }}
      annotations:
  {{- if .Values.slave.annotations }}
{{ toYaml .Values.slave.annotations | indent 8 }}
  {{- end }}
  {{- if .Values.metrics.annotations }}
{{ toYaml .Values.metrics.annotations | indent 8 }}
  {{- end }}
{{- end }}
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- if eq .Values.slave.antiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app: "{{ template "mysql.name" . }}"
                  release: "{{ .Release.Name }}"
      {{- else if eq .Values.slave.antiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "{{ template "mysql.name" . }}"
                  release: "{{ .Release.Name }}"
      {{- end }}
{{- include "mysql.imagePullSecrets" . | indent 6 }}
      {{- if and .Values.volumePermissions.enabled .Values.slave.persistence.enabled }}
      initContainers:
      - name: volume-permissions
        image: "{{ template "mysql.volumePermissions.image" . }}"
        imagePullPolicy: {{ default "" .Values.volumePermissions.image.pullPolicy | quote }}
        command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}", "{{ .Values.slave.persistence.mountPath }}"]
        securityContext:
          runAsUser: 0
        resources: {{ toYaml .Values.volumePermissions.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: "{{ .Values.slave.persistence.mountPath }}"
      {{- end }}
      containers:
      - name: "mysql"
        image: {{ template "mysql.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: MYSQL_REPLICATION_MODE
          value: "slave"
        - name: MYSQL_MASTER_HOST
          value: {{ .Values.kinto.alias }}
        - name: MYSQL_MASTER_PORT_NUMBER
          value: "3306"
        - name: MYSQL_MASTER_ROOT_USER
          value: "root"
        - name: MYSQL_MASTER_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.fullname" . }}
              key: mysql-root-password
        - name: MYSQL_REPLICATION_USER
          value: "{{ .Values.replication.user }}"
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.fullname" . }}
              key: mysql-replication-password
        ports:
        - name: mysql
          containerPort: 3306
        {{- if .Values.slave.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MYSQL_MASTER_ROOT_PASSWORD"]
          initialDelaySeconds: {{ .Values.slave.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.slave.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.slave.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.slave.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.slave.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.slave.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command: ["sh", "-c", "exec mysqladmin status -uroot -p$MYSQL_MASTER_ROOT_PASSWORD"]
          initialDelaySeconds: {{ .Values.slave.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.slave.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.slave.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.slave.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.slave.readinessProbe.failureThreshold }}
        {{- end }}
{{- if .Values.resources.enabled }}
        resources:
          requests:
            memory: {{ .Values.resources.memory }}
            cpu: {{ .Values.resources.cpu }}
          limits:
            memory: {{ .Values.resources.memory }}
            cpu: {{ .Values.resources.cpu }}
{{- end }}
        volumeMounts:
        - name: data
          mountPath: {{ .Values.slave.persistence.mountPath }}
{{- if .Values.slave.config }}
        - name: config
          mountPath: /opt/bitnami/mysql/conf/my.cnf
          subPath: my.cnf
{{- end }}
{{- if .Values.metrics.enabled }}
      - name: metrics
        image: {{ template "mysql.metrics.image" . }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
        env:
        - name: MYSQL_MASTER_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.fullname" . }}
              key: mysql-root-password
        command: [ 'sh', '-c', 'DATA_SOURCE_NAME="root:$MYSQL_MASTER_ROOT_PASSWORD@(localhost:3306)/" /bin/mysqld_exporter' ]
        ports:
        - name: metrics
          containerPort: 9104
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.metrics.resources | indent 10 }}
{{- end }}
      volumes:
      {{- if .Values.slave.config }}
        - name: config
          configMap:
            name: {{ template "mysql.slave.fullname" . }}
      {{- end }}
{{- if .Values.slave.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: "{{ template "mysql.name" . }}"
          component: "slave"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
      spec:
        accessModes:
        {{- range .Values.slave.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.slave.persistence.size | quote }}
        {{ include "mysql.slave.storageClass" . }}
{{- else }}
        - name: "data"
          emptyDir: {}
{{- end }}
      {{- with .Values.slave.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- end }}
