{{- if .Values.replication.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mysql.slave.fullname" . }}
  labels:
    app: "{{ template "mysql.name" . }}"
    chart: {{ template "mysql.chart" . }}
    component: "slave"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: mysql
    port: {{ .Values.service.port }}
    targetPort: mysql
{{- if .Values.metrics.enabled }}
  - name: metrics
    port: 9104
    targetPort: metrics
{{- end }}
  selector:
    app: "{{ template "mysql.name" . }}"
    component: "slave"
    release: "{{ .Release.Name }}"
{{- end }}
